name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:  # для ручного запуска из интерфейса

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        id: fly_deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run database migrations via Fly proxy
        if: success()  
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
         
          fly proxy 5432:5432 -a little-snowflake-3053 &
          sleep 5
          psql "postgres://horoscop:N5NCdtk5HZmM6fU@localhost:5432/<databasename>" -f init_database.sql
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
